# Generated by Django 5.1.6 on 2025-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accept_reject',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
