# Generated by Django 5.1 on 2024-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
