# Generated by Django 4.2.6 on 2024-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acb', '0003_auto_20240902_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
