# Generated by Django 5.1.1 on 2024-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acb', '0005_teacherreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherreg',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
