# Generated by Django 5.1.1 on 2025-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acb', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadnotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
    ]
